{
 "title": "Kubernetes Monitoring Dashboard",
 "description": "Kubernetes Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "time() - kube_pod_start_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart Counts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Phase Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}